export class Schedule {
    constructor(
        public id: number,
        public pk: number,
        public user_id: number,
        public profile_id: number,
        public email: string,
        public profile: any,
        public name: string,
        public user_type: string,
        public technical_mentor: string,
        public date_created: any,
        public no_hours: number,
        public title: string,
        public meet_url: string,
        public date_of_session: number,
        public start: number,
        public end: number,
        public comment: string,
        public likes: any,
        public student_id: number,
        public technical_mentor_id: number,
        public content: string,
        public session: any,
        public module: any,
        public announcement: any,
        public announcement_id: number,
        public announcomment_id: number,
        public session_id: number,
        public module_id: number,
        public comment_id: number,
        public body: string,
        public bio: string,
        public profile_img: any,
    ) { }
}